export enum AuditAction {
  // Authentication
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGIN_SUSPICIOUS = 'LOGIN_SUSPICIOUS',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
  SESSION_REVOKED = 'SESSION_REVOKED',

  // User management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DELETED = 'USER_DELETED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',

  // Roles & permissions administration
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',

  // CMS
  CMS_CONTENT_CREATED = 'CMS_CONTENT_CREATED',
  CMS_CONTENT_UPDATED = 'CMS_CONTENT_UPDATED',
  CMS_CONTENT_DELETED = 'CMS_CONTENT_DELETED',
  CMS_CONTENT_STATUS_CHANGED = 'CMS_CONTENT_STATUS_CHANGED',

  // Media library
  MEDIA_ASSET_UPLOADED = 'MEDIA_ASSET_UPLOADED',
  MEDIA_ASSET_UPDATED = 'MEDIA_ASSET_UPDATED',
  MEDIA_ASSET_DELETED = 'MEDIA_ASSET_DELETED',

  // Organization
  ORG_CREATED = 'ORG_CREATED',
  ORG_UPDATED = 'ORG_UPDATED',
  ORG_MEMBER_ADDED = 'ORG_MEMBER_ADDED',
  ORG_MEMBER_REMOVED = 'ORG_MEMBER_REMOVED',
  ORG_MEMBER_ROLE_CHANGED = 'ORG_MEMBER_ROLE_CHANGED',

  // Client / CRM
  CLIENT_CREATED = 'CLIENT_CREATED',
  CLIENT_UPDATED = 'CLIENT_UPDATED',
  CLIENT_DELETED = 'CLIENT_DELETED',
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_UPDATED = 'LEAD_UPDATED',
  LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',

  // Projects
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_STATUS_CHANGED = 'PROJECT_STATUS_CHANGED',
  PROJECT_DELETED = 'PROJECT_DELETED',

  // Plant Assessment
  ASSESSMENT_CREATED = 'ASSESSMENT_CREATED',
  ASSESSMENT_SUBMITTED = 'ASSESSMENT_SUBMITTED',
  ASSESSMENT_APPROVED = 'ASSESSMENT_APPROVED',
  ASSESSMENT_STATUS_CHANGED = 'ASSESSMENT_STATUS_CHANGED',

  // RFQ
  RFQ_CREATED = 'RFQ_CREATED',
  RFQ_UPDATED = 'RFQ_UPDATED',
  RFQ_SUBMITTED = 'RFQ_SUBMITTED',
  RFQ_CANCELLED = 'RFQ_CANCELLED',

  // Quotation
  QUOTATION_CREATED = 'QUOTATION_CREATED',
  QUOTATION_UPDATED = 'QUOTATION_UPDATED',
  QUOTATION_SUBMITTED_FOR_REVIEW = 'QUOTATION_SUBMITTED_FOR_REVIEW',
  QUOTATION_APPROVED = 'QUOTATION_APPROVED',
  QUOTATION_REJECTED = 'QUOTATION_REJECTED',
  QUOTATION_SENT = 'QUOTATION_SENT',
  QUOTATION_ACCEPTED = 'QUOTATION_ACCEPTED',
  QUOTATION_CONVERTED = 'QUOTATION_CONVERTED',

  // Contract
  CONTRACT_CREATED = 'CONTRACT_CREATED',
  CONTRACT_UPDATED = 'CONTRACT_UPDATED',
  CONTRACT_APPROVED = 'CONTRACT_APPROVED',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  CONTRACT_TERMINATED = 'CONTRACT_TERMINATED',

  // Finance
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  INVOICE_CANCELLED = 'INVOICE_CANCELLED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_REVERSED = 'PAYMENT_REVERSED',

  // Documents
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_REVISED = 'DOCUMENT_REVISED',
  DOCUMENT_REVIEWED = 'DOCUMENT_REVIEWED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_SUPERSEDED = 'DOCUMENT_SUPERSEDED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  DOCUMENT_DOWNLOADED = 'DOCUMENT_DOWNLOADED',

  // Procurement
  REQUISITION_CREATED = 'REQUISITION_CREATED',
  PROCUREMENT_APPROVED = 'PROCUREMENT_APPROVED',
  PURCHASE_ORDER_CREATED = 'PURCHASE_ORDER_CREATED',
  DELIVERY_RECEIVED = 'DELIVERY_RECEIVED',

  // HSE
  HSE_INCIDENT_CREATED = 'HSE_INCIDENT_CREATED',
  HSE_INCIDENT_UPDATED = 'HSE_INCIDENT_UPDATED',
  HSE_INCIDENT_CLOSED = 'HSE_INCIDENT_CLOSED',
  HSE_INSPECTION_CREATED = 'HSE_INSPECTION_CREATED',

  // Commissioning
  COMMISSIONING_TEST_CREATED = 'COMMISSIONING_TEST_CREATED',
  COMMISSIONING_TEST_PASSED = 'COMMISSIONING_TEST_PASSED',
  COMMISSIONING_TEST_FAILED = 'COMMISSIONING_TEST_FAILED',
  COMMISSIONING_APPROVED = 'COMMISSIONING_APPROVED',
  HANDOVER_COMPLETED = 'HANDOVER_COMPLETED',

  // Assets / Maintenance
  ASSET_CREATED = 'ASSET_CREATED',
  ASSET_UPDATED = 'ASSET_UPDATED',
  MAINTENANCE_CREATED = 'MAINTENANCE_CREATED',
  MAINTENANCE_COMPLETED = 'MAINTENANCE_COMPLETED',
  MAINTENANCE_CLOSED = 'MAINTENANCE_CLOSED',
  WARRANTY_CLAIMED = 'WARRANTY_CLAIMED',

  // Support
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_RESOLVED = 'TICKET_RESOLVED',
  TICKET_CLOSED = 'TICKET_CLOSED',

  // Operations ERP — Inventory
  INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED',
  INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED',
  INVENTORY_ITEM_DELETED = 'INVENTORY_ITEM_DELETED',
  INVENTORY_STOCK_ADJUSTED = 'INVENTORY_STOCK_ADJUSTED',
  INVENTORY_CATEGORY_CREATED = 'INVENTORY_CATEGORY_CREATED',
  INVENTORY_CATEGORY_UPDATED = 'INVENTORY_CATEGORY_UPDATED',
  INVENTORY_CATEGORY_DELETED = 'INVENTORY_CATEGORY_DELETED',
  STORE_CREATED = 'STORE_CREATED',
  STORE_UPDATED = 'STORE_UPDATED',
  STORE_DELETED = 'STORE_DELETED',

  // Operations ERP — Sales / POS
  SALE_CREATED = 'SALE_CREATED',
  SALE_VOIDED = 'SALE_VOIDED',
  SALE_REFUNDED = 'SALE_REFUNDED',

  // Operations ERP — Customers
  ERP_CUSTOMER_CREATED = 'ERP_CUSTOMER_CREATED',
  ERP_CUSTOMER_UPDATED = 'ERP_CUSTOMER_UPDATED',
  ERP_CUSTOMER_DELETED = 'ERP_CUSTOMER_DELETED',

  // Operations ERP — Debt
  DEBT_ACCOUNT_CREATED = 'DEBT_ACCOUNT_CREATED',
  DEBT_ACCOUNT_UPDATED = 'DEBT_ACCOUNT_UPDATED',
  DEBT_PAYMENT_RECORDED = 'DEBT_PAYMENT_RECORDED',

  // Operations ERP — Expenses
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_UPDATED = 'EXPENSE_UPDATED',
  EXPENSE_DELETED = 'EXPENSE_DELETED',
  EXPENSE_CATEGORY_CREATED = 'EXPENSE_CATEGORY_CREATED',
  EXPENSE_CATEGORY_UPDATED = 'EXPENSE_CATEGORY_UPDATED',
  EXPENSE_CATEGORY_DELETED = 'EXPENSE_CATEGORY_DELETED',

  // Operations ERP — Accounts
  FINANCIAL_ACCOUNT_CREATED = 'FINANCIAL_ACCOUNT_CREATED',
  FINANCIAL_ACCOUNT_UPDATED = 'FINANCIAL_ACCOUNT_UPDATED',
  FINANCIAL_ACCOUNT_DELETED = 'FINANCIAL_ACCOUNT_DELETED',
  ACCOUNT_MANUAL_ENTRY_CREATED = 'ACCOUNT_MANUAL_ENTRY_CREATED',

  // Operations ERP — Branches & settings
  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_UPDATED = 'BRANCH_UPDATED',
  BRANCH_DELETED = 'BRANCH_DELETED',
  BRANCH_SET_DEFAULT = 'BRANCH_SET_DEFAULT',
  BRANCH_SETTINGS_UPDATED = 'BRANCH_SETTINGS_UPDATED',

  // Operations ERP — Vat leach
  VAT_LEACH_UNIT_CREATED = 'VAT_LEACH_UNIT_CREATED',
  VAT_LEACH_UNIT_UPDATED = 'VAT_LEACH_UNIT_UPDATED',
  VAT_LEACH_UNIT_DELETED = 'VAT_LEACH_UNIT_DELETED',
  VAT_LEACH_RENTAL_CREATED = 'VAT_LEACH_RENTAL_CREATED',
  VAT_LEACH_RENTAL_UPDATED = 'VAT_LEACH_RENTAL_UPDATED',
  VAT_LEACH_RENTAL_DELETED = 'VAT_LEACH_RENTAL_DELETED',
  VAT_LEACH_PAYMENT_RECORDED = 'VAT_LEACH_PAYMENT_RECORDED',

  // Operations ERP — Stock piles
  STOCK_PILE_CREATED = 'STOCK_PILE_CREATED',
  STOCK_PILE_UPDATED = 'STOCK_PILE_UPDATED',
  STOCK_PILE_DELETED = 'STOCK_PILE_DELETED',
  STOCK_PILE_MOVEMENT_RECORDED = 'STOCK_PILE_MOVEMENT_RECORDED',

  // Operations ERP — Site security
  SECURITY_LOG_CREATED = 'SECURITY_LOG_CREATED',
  SECURITY_LOG_UPDATED = 'SECURITY_LOG_UPDATED',
  SECURITY_LOG_DELETED = 'SECURITY_LOG_DELETED',
  SECURITY_LOG_RESOLVED = 'SECURITY_LOG_RESOLVED',

  // Operations ERP — HR
  STAFF_CREATED = 'STAFF_CREATED',
  STAFF_UPDATED = 'STAFF_UPDATED',
  STAFF_DELETED = 'STAFF_DELETED',
  PAYROLL_RUN_CREATED = 'PAYROLL_RUN_CREATED',
  PAYROLL_RUN_APPROVED = 'PAYROLL_RUN_APPROVED',
  PAYROLL_RUN_PAID = 'PAYROLL_RUN_PAID',
  PAYROLL_ENTRY_UPDATED = 'PAYROLL_ENTRY_UPDATED',
  LEAVE_REQUEST_CREATED = 'LEAVE_REQUEST_CREATED',
  LEAVE_REQUEST_UPDATED = 'LEAVE_REQUEST_UPDATED',
  LEAVE_REQUEST_DELETED = 'LEAVE_REQUEST_DELETED',
  LEAVE_REQUEST_APPROVED = 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_DENIED = 'LEAVE_REQUEST_DENIED',
  LEAVE_RETURN_RECORDED = 'LEAVE_RETURN_RECORDED',
  ATTENDANCE_CHECKED_IN = 'ATTENDANCE_CHECKED_IN',
  ATTENDANCE_CHECKED_OUT = 'ATTENDANCE_CHECKED_OUT',

  // Operations ERP — Visitors
  VISITOR_REGISTERED = 'VISITOR_REGISTERED',
  VISITOR_UPDATED = 'VISITOR_UPDATED',
  VISITOR_DELETED = 'VISITOR_DELETED',
  VISITOR_CHECKED_OUT = 'VISITOR_CHECKED_OUT',
}

export interface AuditContext {
  organizationId?: string;
  userId: string;
  action: AuditAction;
  entity: string;
  entityId?: string;
  oldValues?: Record<string, unknown>;
  newValues?: Record<string, unknown>;
  ipAddress?: string;
  userAgent?: string;
  metadata?: Record<string, unknown>;
}
