/**
 * Gallery image pipeline.
 *
 * 1. Drop original photos (jpg/jpeg/png/tif/heic/webp) into:
 *      web/public/images/gallery/_source/
 *    Optionally group them into subfolders — the subfolder name becomes the
 *    gallery "category" filter chip, e.g. _source/Gold processing/DSC_01.jpg.
 *
 * 2. Run:  node web/scripts/convert-gallery.mjs
 *
 * Each image is re-encoded to .webp at ORIGINAL resolution (no downscsale) with
 * high quality + max effort, preserving sharpness. The optimized files are
 * written to web/public/images/gallery/ and web/src/config/gallery.ts is
 * regenerated with real width/height so the grid never shifts layout.
 *
 * Requires sharp:  pnpm -C web add -D sharp
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = path.resolve(__dirname, '..');
const SOURCE_DIR = path.join(WEB_ROOT, 'public/images/gallery/_source');
const OUT_DIR = path.join(WEB_ROOT, 'public/images/gallery');
const MANIFEST = path.join(WEB_ROOT, 'src/config/gallery.ts');

const INPUT_EXT = new Set(['.jpg', '.jpeg', '.png', '.tif', '.tiff', '.heic', '.webp', '.avif']);
const WEBP_OPTS = { quality: 90, effort: 6 }; // high quality, no resize → sharp originals

let sharp;
try {
  sharp = (await import('sharp')).default;
} catch {
  console.error(
    '\n  sharp is not installed. Run:  pnpm -C web add -D sharp\n  then re-run this script.\n',
  );
  process.exit(1);
}

function titleFromFilename(file) {
  return path
    .basename(file, path.extname(file))
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function walk(dir, category = null) {
  const out = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await walk(full, e.name)));
    } else if (INPUT_EXT.has(path.extname(e.name).toLowerCase())) {
      out.push({ full, category });
    }
  }
  return out;
}

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });
  const files = await walk(SOURCE_DIR);

  if (files.length === 0) {
    console.log(
      `No source images found in ${SOURCE_DIR}\n` +
        'Drop the gallery originals there (subfolders become categories) and re-run.',
    );
    return;
  }

  files.sort((a, b) => a.full.localeCompare(b.full));
  const manifest = [];
  let n = 0;

  for (const { full, category } of files) {
    n += 1;
    const prefix = category ? `${slugify(category)}-` : '';
    const base = `${prefix}${slugify(path.basename(full, path.extname(full)))}` || `photo-${n}`;
    const outName = `${base}.webp`;
    const outPath = path.join(OUT_DIR, outName);

    const img = sharp(full, { failOn: 'none' }).rotate(); // honour EXIF orientation
    const meta = await img.metadata();
    await img.webp(WEBP_OPTS).toFile(outPath);

    // Post-rotation dimensions.
    const finalMeta = await sharp(outPath).metadata();
    manifest.push({
      src: `/images/gallery/${outName}`,
      width: finalMeta.width ?? meta.width ?? 1600,
      height: finalMeta.height ?? meta.height ?? 1067,
      alt: `${titleFromFilename(full)} — Green Ngoria Supplies Limited`,
      category: category ?? undefined,
    });
    console.log(`  ✓ ${outName}  (${finalMeta.width}×${finalMeta.height})`);
  }

  const body =
    `/**\n` +
    ` * Gallery manifest — GENERATED by web/scripts/convert-gallery.mjs.\n` +
    ` * Do not edit by hand; re-run the script to regenerate.\n` +
    ` */\n\n` +
    `export interface GalleryImage {\n` +
    `  src: string;\n  width: number;\n  height: number;\n  alt: string;\n  category?: string;\n}\n\n` +
    `export const galleryImages: GalleryImage[] = ${JSON.stringify(manifest, null, 2)};\n`;

  await fs.writeFile(MANIFEST, body, 'utf8');
  console.log(`\nWrote ${manifest.length} images to the gallery manifest.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
