export enum NotificationType {
  QUOTATION_APPROVED = 'QUOTATION_APPROVED',
  QUOTATION_REJECTED = 'QUOTATION_REJECTED',
  QUOTATION_SENT = 'QUOTATION_SENT',
  RFQ_RECEIVED = 'RFQ_RECEIVED',
  ASSESSMENT_SUBMITTED = 'ASSESSMENT_SUBMITTED',
  ASSESSMENT_APPROVED = 'ASSESSMENT_APPROVED',
  DOCUMENT_APPROVAL_REQUIRED = 'DOCUMENT_APPROVAL_REQUIRED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_OVERDUE = 'INVOICE_OVERDUE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PROJECT_MILESTONE_REACHED = 'PROJECT_MILESTONE_REACHED',
  PROJECT_STATUS_CHANGED = 'PROJECT_STATUS_CHANGED',
  HSE_INCIDENT_CREATED = 'HSE_INCIDENT_CREATED',
  COMMISSIONING_TEST_FAILED = 'COMMISSIONING_TEST_FAILED',
  COMMISSIONING_APPROVED = 'COMMISSIONING_APPROVED',
  MAINTENANCE_OVERDUE = 'MAINTENANCE_OVERDUE',
  WARRANTY_EXPIRING = 'WARRANTY_EXPIRING',
  SUPPORT_TICKET_CREATED = 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_UPDATED = 'SUPPORT_TICKET_UPDATED',
  SUPPORT_TICKET_RESOLVED = 'SUPPORT_TICKET_RESOLVED',
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  CONTRACT_REQUIRES_APPROVAL = 'CONTRACT_REQUIRES_APPROVAL',
  PROCUREMENT_REQUIRES_APPROVAL = 'PROCUREMENT_REQUIRES_APPROVAL',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
}

export interface CreateNotificationDto {
  userId: string;
  organizationId?: string;
  type: NotificationType;
  title: string;
  message: string;
  entityType?: string;
  entityId?: string;
  actionUrl?: string;
  channels?: NotificationChannel[];
  metadata?: Record<string, unknown>;
}
