/**
 * Gallery manifest — the photographs shown on /gallery.
 *
 * This file is GENERATED by `web/scripts/convert-gallery.mjs`, which converts
 * source images (dropped into `web/public/images/gallery/_source/`) to
 * optimized `.webp` at original resolution and writes the entries below with
 * real width/height (so the grid reserves correct aspect ratios and Next.js
 * can size the images without layout shift).
 *
 * To (re)generate: drop originals in the _source folder and run
 *   node web/scripts/convert-gallery.mjs
 */

export interface GalleryImage {
  /** Public path to the optimized webp, e.g. /images/gallery/site-01.webp */
  src: string;
  width: number;
  height: number;
  alt: string;
  /** Optional grouping shown as a filter chip, e.g. "Gold processing". */
  category?: string;
}

export const galleryImages: GalleryImage[] = [];
